title: Cristian David Pachacama
description: Blog de Información Académica y Profesional
author: Cristian Pachacama
logo: /static/img/avatar.png
github: https://github.com/ashutosh2k12
about: Ingeniero Matemático (Estadística, Investigación de Operaciones)

baseurl: ""
url: "http://aboutashu.com/hcz-jekyll-blog"

disqus_shortname: CristianPachacama
google_analytics: UA-72862926-1

share:
  twitter_username: \#CristianDavidPS
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
